# Generated by Django 4.1.1 on 2022-10-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="user",),
    ]
